### ISSUE TITLE
Default selection

### ISSUE THREAD

**Issue by pomdtr** [abingham/vsc-around#6]
When no word is selected, it could be useful to select the current word by default.

**Comment by abingham** [comment]
This is a very good idea.

**Comment by abingham** [comment]
It looks like the `textEditor.document.getWordRangeAtPosition` is what we can use to get the "word" at the cursor.

However, it seems that code always thinks there's at least one selection. That is, if my cursor is over a character - even though I haven't really "selected" anything - it reports that I have one selection, i.e. the character I'm over. So we don't have a good signal (that I know of) when there's nothing selected.

This is a problem because perhaps the user really *does* want to surround just a single character rather than select the current word. How can we tell the difference? Maybe we can't, or maybe there's something else we can check.

If we can't tell the difference, then we might need some setting that dis/enables selection of the word under the cursor.

**Comment by abingham** [comment]
Ah, ok, I shouldn't program when I'm sleep deprived. When the use hasn't selected anything, there *is* still a selection, but it's empty, i.e. `selection.start == selection.end`. So I think we can trigger off of that.

**Comment by abingham** [comment]
This is implemented in 0.2.0. 

@pomdtr I'll close this, but let me know if it doesn't work (or doesn't work as expected).
